<a href="https://colab.research.google.com/github/nancyngh13-debug/ciencia-de-datos/blob/aprendiendoPython/An%C3%A1lisis_de_Datos_con_Pandas_Carga_y_Exploraci%C3%B3n_de_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NANCY GALLEGO 24/08/2026

In [33]:
import kagglehub
import os # Import the os module

# Download latest version
path = kagglehub.dataset_download("tunguz/online-retail")

print("Path to dataset files:", path)

# This line would have caused the _IncompleteInputError previously (with a missing closing parenthesis).
# It also required importing the 'os' module. Now it's corrected.
print("Dataset files:", os.listdir(path))

Using Colab cache for faster access to the 'online-retail' dataset.
Path to dataset files: /kaggle/input/online-retail
Dataset files: ['Online_Retail.csv']

sv(path)  en caso de excel: data_excel = pd.read_excel(path) en caso de json: data_json = pd.read(path)

importar pandas si es csv: path = ruta + variable = pd.read_

In [34]:
import pandas as pd
file_path = '/kaggle/input/online-retail/Online_Retail.csv'
sales_data = pd.read_csv(file_path, encoding='latin-1')
print(sales_data.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

In [35]:
import numpy as np
data = np.array([[1,2,3], [4,5,6],[7,8,9]])

df_from_array = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df_from_array)
#

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [36]:
data =[[1,'Jhon', 22], [2,'Anna', 24]]

df_from_list = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])
print(df_from_list)
#

   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24

In [37]:
data = [{'ID': 1, 'Name': 'Jhon', 'Age': 22}]
df_from_dict = pd.DataFrame([data])
print(df_from_dict)

                                      0
0  {'ID': 1, 'Name': 'Jhon', 'Age': 22}

In [38]:
data = {'ID': [1,2,3], 'Name': ['Jhon', 'Anna','mike'], 'Age': [22, 24,21]}
df_from_dict = pd.DataFrame(data)
print(df_from_dict)

   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  mike   21

series

In [39]:
import pandas as pd
data = {'ID': pd.Series([1,2,3]),
        'Name': pd.Series(['Jhon', 'Anna','mike']),
        'Age': pd.Series([22, 24,21])}
df_from_series_dict= pd.DataFrame(data)
display(df_from_series_dict)

   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  mike   21

estructuras de datos y funciones

In [40]:
import pandas as pd

path = '/root/.cache/kagglehub/datasets/tunguz/online-retail/versions/1/Online_Retail.csv'
retail_data = pd.read_csv(path, encoding='latin-1')
print(retail_data.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

In [41]:
#Nombres de columnas
columns_names = retail_data.columns
print(columns_names)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [42]:
num_rows = retail_data.shape[0]
print('Numero de filas', num_rows)
num_columns = retail_data.shape[1]
print('Numero de columnas', num_columns)

Numero de filas 541909
Numero de columnas 8

In [43]:
dailysales = retail_data['Quantity']
print(dailysales)

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64

In [44]:
dailysales = retail_data['Quantity'] * retail_data['UnitPrice']
print(dailysales)
#

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Length: 541909, dtype: float64

In [45]:
summary = retail_data.describe()
print(summary)

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [46]:
mean_value = dailysales.mean()
print('la media es', mean_value)

la media es 17.98779487699964

In [47]:
median_value = dailysales.median()
print('la mediana es', median_value)

la mediana es 9.75

In [48]:
sum_value = dailysales.sum()
print('la suma total es', sum_value)

la suma total es 9747747.933999998

In [49]:
count_values = dailysales.count()
print('el numero de valores es', count_values)

el numero de valores es 541909

In [50]:
import pandas as pd
dailysales = pd.Series([10,20, None, 40,50])

#Suma de Quantity
total_sum = dailysales.sum()
print("Suma de quantity", total_sum)

#Conteo de Quantity
count_values = dailysales.count()
print("Conteo de quantity", count_values)

#Media de Quantity
mean_value = dailysales.mean()
print("Media de quantity", mean_value)

Suma de quantity 120.0
Conteo de quantity 4
Media de quantity 30.0

METODO GET EN PANDAS

In [51]:
retail_data.head(8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/10 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/10 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/10 8:28,1.85,17850.0,United Kingdom

iloc y loc espesificando etiqueta

iloc vs loc en Pandas para filtrar datos

In [52]:
first_row = retail_data.iloc[0]
print(first_row)

InvoiceNo                                  536365
StockCode                                  85123A
Description    WHITE HANGING HEART T-LIGHT HOLDER
Quantity                                        6
InvoiceDate                          12/1/10 8:26
UnitPrice                                    2.55
CustomerID                                17850.0
Country                            United Kingdom
Name: 0, dtype: object

In [53]:
first_row = retail_data.iloc[4]
print(first_row)

InvoiceNo                              536365
StockCode                              84029E
Description    RED WOOLLY HOTTIE WHITE HEART.
Quantity                                    6
InvoiceDate                      12/1/10 8:26
UnitPrice                                3.39
CustomerID                            17850.0
Country                        United Kingdom
Name: 4, dtype: object

In [54]:
first_five_row = retail_data.iloc[:5]
print(first_five_row)
#

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

In [55]:
subset = retail_data.loc[:, ['InvoiceNo', 'StockCode', 'Description']]
print(subset)
#

       InvoiceNo StockCode                          Description
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...          ...       ...                                  ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT

[541909 rows x 3 columns]

In [56]:
retail_value = retail_data.iloc[:3,:2]
print(retail_value)

  InvoiceNo StockCode
0    536365    85123A
1    536365     71053
2    536365    84406B

In [57]:
retail_value = retail_data.iloc[1,3]
print(retail_value)

6

In [58]:
row_index_3 = retail_data.loc[3]
print(row_index_3)

InvoiceNo                                   536365
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                         6
InvoiceDate                           12/1/10 8:26
UnitPrice                                     3.39
CustomerID                                 17850.0
Country                             United Kingdom
Name: 3, dtype: object

In [59]:
row_index_0_to_4 = retail_data.loc[0:4]
print(row_index_0_to_4)

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

In [60]:
quantity_column = retail_data.loc[:, 'Quantity']
print(quantity_column)

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64

In [61]:
quantity_unitprices_column = retail_data.loc[:, ['Quantity', 'UnitPrice']]
print(quantity_unitprices_column)

        Quantity  UnitPrice
0              6       2.55
1              6       3.39
2              8       2.75
3              6       3.39
4              6       3.39
...          ...        ...
541904        12       0.85
541905         6       2.10
541906         4       4.15
541907         4       4.15
541908         3       4.95

[541909 rows x 2 columns]

Manejo de Datos Faltantes en Pandas: Identificación y Tratamiento

In [62]:
missing_data = retail_data.isna()
print(missing_data)

        InvoiceNo  StockCode  Description  Quantity  InvoiceDate  UnitPrice  \
0           False      False        False     False        False      False
1           False      False        False     False        False      False
2           False      False        False     False        False      False
3           False      False        False     False        False      False
4           False      False        False     False        False      False
...           ...        ...          ...       ...          ...        ...
541904      False      False        False     False        False      False
541905      False      False        False     False        False      False
541906      False      False        False     False        False      False
541907      False      False        False     False        False      False
541908      False      False        False     False        False      False

        CustomerID  Country
0            False    False
1            False    False
2            False    False
3            False    False
4            False    False
...            ...      ...
541904       False    False
541905       False    False
541906       False    False
541907       False    False
541908       False    False

[541909 rows x 8 columns]

In [63]:
print(missing_data)

        InvoiceNo  StockCode  Description  Quantity  InvoiceDate  UnitPrice  \
0           False      False        False     False        False      False
1           False      False        False     False        False      False
2           False      False        False     False        False      False
3           False      False        False     False        False      False
4           False      False        False     False        False      False
...           ...        ...          ...       ...          ...        ...
541904      False      False        False     False        False      False
541905      False      False        False     False        False      False
541906      False      False        False     False        False      False
541907      False      False        False     False        False      False
541908      False      False        False     False        False      False

        CustomerID  Country
0            False    False
1            False    False
2            False    False
3            False    False
4            False    False
...            ...      ...
541904       False    False
541905       False    False
541906       False    False
541907       False    False
541908       False    False

[541909 rows x 8 columns]

In [64]:
missing_data_count = retail_data.isna().sum()
print('conteo de datos faltantes por columna:\n', missing_data_count)

conteo de datos faltantes por columna:
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [65]:
no_missing_row = retail_data.dropna()
print('Datos sin filas con valores faltantes:\n', no_missing_row)

Datos sin filas con valores faltantes:
        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
541904  12/9/11 12:50       0.85     12680.0          France
541905  12/9/11 12:50       2.10     12680.0          France
541906  12/9/11 12:50       4.15     12680.0          France
541907  12/9/11 12:50       4.15     12680.0          France
541908  12/9/11 12:50       4.95     12680.0          France

[406829 rows x 8 columns]

In [72]:
retail_data_fillef_zeros = retail_data.fillna(0)
retail_data_fillef_zeros_count = retail_data.isna().sum()
print(retail_data_fillef_zeros_count)

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [73]:
mean_unit_price = retail_data['UnitPrice'].mean()
retail_data['UnitPrice'].fillna(mean_unit_price, inplace=True)

/tmp/ipykernel_1699/1685490996.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  retail_data['UnitPrice'].fillna(mean_unit_price, inplace=True)

In [74]:
mean_unit_price = retail_data['UnitPrice'].mean()
retail_data_filled_mean = retail_data.fillna(mean_unit_price)
retail_data_filled_mean_count = retail_data_filled_mean.isna().sum()
print(retail_data_filled_mean_count)

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [75]:
mean_unit_price = retail_data['UnitPrice'].mean()
retail_data_filler_mean = retail_data['UnitPrice'].fillna(mean_unit_price)
print(retail_data_filled_mean)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
541904  12/9/11 12:50       0.85     12680.0          France
541905  12/9/11 12:50       2.10     12680.0          France
541906  12/9/11 12:50       4.15     12680.0          France
541907  12/9/11 12:50       4.15     12680.0          France
541908  12/9/11 12:50       4.95     12680.0          France

[541909 rows x 8 columns]